name: Android CI

on:
 # push:
    # branches: [ "master" ]
  pull_request:
    branches: [ "master", "starter"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Android Emulator Runner
      uses: ReactiveCircus/android-emulator-runner@v2.28.0
      with:
       api-level: 23
       target: default
       arch: x86
       profile: Nexus 6
       script: ./gradlew connectedCheck --stacktrace
